### ISSUE TITLE
What does "Response time" do?

### ISSUE THREAD

**Issue by CamilleScholtz** [MihaiBojescu/Linux-notifier-Android#1]
Thanks for this great app btw!

**Comment by MihaiBojescu** [comment]
This was the idea: There was a thread which pinged every IP address from *.*.*.2 to *.*.*.254. Ping sends a request to the device and waits for a response. "Response time" was "how much should the ping service wait for a response until it pings the next address in the checklist".
This is obsolete now, as everything is done with UDP multicast now, which means instant subnet discovery, so "response time" is no longer needed.

By the way, thank you for the kind words! I plan to extend it whenever I can.

**Comment by MihaiBojescu** [comment]
Fixed in the latest release.
